export const UPDATE_ACTIVITY_BY_TAG = 'UPDATE_ACTIVITY_BY_TAG';
export const UPDATE_ACTIVITY_BY_TITLE = 'UPDATE_ACTIVITY_BY_TITLE';
export const UPDATE_ACTIVITY_BY_PAGER = 'UPDATE_ACTIVITY_BY_PAGE';

export const REQUEST_ACTIVITY_START = 'REQUEST_ACTIVITY_START';
export const REQUEST_ACTIVITY_SUCCESS = 'REQUEST_ACTIVITY_SUCCESS';
export const REQUEST_ACTIVITY_FAIL = 'REQUEST_ACTIVITY_FAIL';


export const GET_TAGS = 'GET_TAGS';
export const UPDATE_TAG_STATE = 'UPDATE_TAG_STATE';

export const GET_MEMBERS = 'GET_MEMBERS';

export const GET_ACTIVITY = 'GET_ACTIVITY';
